#!/bin/bash -ex

cd "$(dirname "$0")/.."

# Colors
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"

cargo fmt -- --check \
    || { echo "\n${RED}ERROR${RESET}: Must run \`cargo fmt\` before submitting."; exit 1; }

cargo test

for crate in tempdb_cockroach; do
    pushd $crate
    perl -0777 -pe 's/.*## Usage\n\n```rust\n(.*)```.*/$1/s' README.md \
        | colordiff tests/usage.rs - \
        || { echo "\n${RED}ERROR${RESET}: Usage in $package/README.md differs from $package/tests/usage.rs."; exit 1; }
    popd
done

printf "Presubmits ${GREEN}PASSED${RESET}.\n\n"
